repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      name: "Ruff linter"
      args: [ src/netbox_contract/ ]
- repo: local
  hooks:
    - id: django-check
      name: "Django system check"
      description: "Run Django's internal check for common problems"
      entry: python ../netbox/netbox/manage.py check
      language: system
      pass_filenames: false
      types: [python]
    - id: django-makemigrations
      name: "Django migrations check"
      description: "Check for any missing Django migrations"
      entry: python ../netbox/netbox/manage.py makemigrations --check
      language: system
      pass_filenames: false
      types: [python]
