# Generated by Django 4.0.8 on 2023-01-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('circuits', '0038_cabling_cleanup'),
        ('netbox_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='circuit',
            field=models.ManyToManyField(
                related_name='contracts', to='circuits.circuit'
            ),
        ),
        migrations.AlterField(
            model_name='contract',
            name='external_partie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contracts',
                to='netbox_contract.serviceprovider',
            ),
        ),
    ]
