# Generated by Django 4.1.5 on 2023-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0006_alter_contract_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
