# Generated by Django 4.1.5 on 2023-01-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0012_remove_invoice_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='documents',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='documents',
            field=models.URLField(blank=True),
        ),
    ]
