# Generated by Django 4.1.9 on 2023-06-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0015_contractassignement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='child',
                to='netbox_contract.contract',
            ),
        ),
    ]
