# Generated by Django 4.1.9 on 2023-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0016_contract_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='accounting_dimensions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
