# Generated by Django 4.2.5 on 2023-11-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0019_auto_20230924_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='external_partie',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contracts',
                to='netbox_contract.serviceprovider',
            ),
        ),
    ]
