# Generated by Django 4.2.11 on 2024-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0024_remove_contract_external_partie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='circuit',
        ),
        migrations.AlterField(
            model_name='contractassignment',
            name='contract',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',
                to='netbox_contract.contract',
            ),
        ),
    ]
