# Generated by Django 5.0.6 on 2024-07-13 09:43

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_contract', '0028_invoiceline_accounting_dimensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='accounting_dimensions',
        ),
        migrations.CreateModel(
            name='AccountingDimension',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=utilities.json.CustomFieldJSONEncoder,
                    ),
                ),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                (
                    'tags',
                    taggit.managers.TaggableManager(
                        through='extras.TaggedItem', to='extras.Tag'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='accounting_dimensions',
            field=models.ManyToManyField(to='netbox_contract.accountingdimension'),
        ),
    ]
