# Generated by Django 5.0.6 on 2024-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0029_remove_invoiceline_accounting_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='accounting_dimensions',
            field=models.ManyToManyField(
                blank=True,
                related_name='invoicelines',
                to='netbox_contract.accountingdimension',
            ),
        ),
    ]
