# Generated by Django 5.0.6 on 2024-07-24 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'netbox_contract',
            '0032_alter_invoice_period_end_alter_invoice_period_start_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='invoice_template',
        ),
    ]
