# Generated by Django 5.0.6 on 2024-08-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0035_accountingdimension_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='accounting_dimensions',
            field=models.ManyToManyField(
                blank=True, to='netbox_contract.accountingdimension'
            ),
        ),
    ]
