# Generated by Django 5.0.10 on 2025-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0036_alter_invoiceline_accounting_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notice_period',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
    ]
