# Generated by Django 5.2.3 on 2025-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0129_fix_script_paths"),
        ("netbox_contract", "0041_contracttype_contract_contract_type"),
        ("tenancy", "0020_remove_contactgroupmembership"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contract",
            name="netbox_cont_externa_6343fb_idx",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="external_partie_object_id",
            new_name="external_party_object_id",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="external_partie_object_type",
            new_name="external_party_object_type",
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="internal_partie",
            new_name="internal_party",
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["external_party_object_type", "external_party_object_id"],
                name="netbox_cont_externa_e3f507_idx",
            ),
        ),
    ]
