# Generated by Django 5.2.3 on 2025-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "netbox_contract",
            "0042_remove_contract_netbox_cont_externa_6343fb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="posted", max_length=50),
        ),
    ]
