# Generated by Django 5.2.3 on 2025-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_contract", "0043_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="notice_warning",
            field=models.BooleanField(default=False),
        ),
    ]
