# Generated by Django 6.0.8 on 2026-09-26 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_contract", "0045_convert_legacy_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractline",
            name="replaces",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_by",
                to="netbox_contract.contractline",
            ),
        ),
    ]
