# Generated by Django 6.0.8 on 2026-09-26 20:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def copy_contract_line_prices(apps, schema_editor):
    """Existing invoice lines that reference a contract line take its unit and unit price; amounts are unchanged."""
    InvoiceLine = apps.get_model('netbox_contract', 'InvoiceLine')
    ContractLine = apps.get_model('netbox_contract', 'ContractLine')
    lines = ContractLine.objects.filter(pk=OuterRef('contract_line'))
    InvoiceLine.objects.filter(contract_line__isnull=False, unit__isnull=True, unit_price__isnull=True).update(
        unit=Subquery(lines.values('unit')[:1]),
        unit_price=Subquery(lines.values('unit_price')[:1]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_contract", "0046_contractline_replaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoicelines",
                to="netbox_contract.unit",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.RunPython(copy_contract_line_prices, migrations.RunPython.noop),
    ]
