# Generated by Django 6.0.8 on 2026-09-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_contract", "0047_invoiceline_unit_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="draft", max_length=50),
        ),
    ]
