# Generated by Django 4.0.8 on 2022-11-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0038_cabling_cleanup'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='object_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='circuit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='circuits.circuit'),
            preserve_default=False,
        ),
    ]
