# Generated by Django 4.0.8 on 2022-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_circuit_contract_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='initial_term',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='mrc',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='nrc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_term',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='periode_start',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
