# Generated by Django 4.0.8 on 2022-11-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_initial_term_contract_invoice_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='periode_start',
            new_name='period_start',
        ),
    ]
