# Generated by Django 4.0.8 on 2022-11-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0038_cabling_cleanup'),
        ('extras', '0077_customlink_extend_text_and_url'),
        ('contracts', '0002_remove_contract_content_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractInvoice',
            new_name='Invoice',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='contract',
            name='circuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='circuits.circuit'),
        ),
    ]
