from django.urls import include, path
from netbox.views.generic import ObjectChangeLogView
from utilities.urls import get_model_urls
from . import models, views

urlpatterns = [
    # Providers
    path('providers/',
        include(
            get_model_urls(
                'circuits',
                'provider',
                detail=False
            )
        )
    ),
    path('providers/<int:pk>/',
        include(
            get_model_urls(
                'circuits', 
                'provider'
            )
        )
    ),
    # Provider Accounts
    path('provider-accounts/',
        include(
            get_model_urls(
                'circuits',
                'provideraccount',
                detail=False
            )
        )
    ),
    path('provider-accounts/<int:pk>/',
        include(
            get_model_urls(
                'circuits',
                'provideraccount'
            )
        )
    ),

    # Contracts
    path('contracts/',
        views.ContractListView.as_view(),
        name='contract_list'
    ),
    path('contracts/add/',
        views.ContractEditView.as_view(),
        name='contract_add'
    ),
    path('contracts/import/',
        views.ContractBulkImportView.as_view(),
        name='contract_bulk_import',
    ),
    path('contracts/edit/',
        views.ContractBulkEditView.as_view(),
        name='contract_bulk_edit',
    ),
    path('contracts/delete/',
        views.ContractBulkDeleteView.as_view(),
        name='contract_bulk_delete',
    ),
    path('contracts/<int:pk>/',
        include(get_model_urls('netbox_contracts', 'contract')),
        name='contract',
    ),
    path('contracts/<int:pk>/edit/',
        views.ContractEditView.as_view(),
        name='contract_edit',
    ),
    path('contracts/<int:pk>/delete/',
        views.ContractDeleteView.as_view(),
        name='contract_delete',
    ),
    path('contracts/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='contract_changelog',
        kwargs={'model': models.Contract},
    ),
    path('contracts/<int:pk>/assignments/',
        views.ContractAssignmentTabView.as_view(),
        name='contract_assignment_list',
    ),
    # Service Level Agreements
    path('servicelevelagreement/', 
         views.ServiceLevelAgreementListView.as_view(), name='servicelevelagreement_list'),
    path('servicelevelagreement/add/', 
         views.ServiceLevelAgreementEditView.as_view(), name='servicelevelagreement_add'),
    path('servicelevelagreement/import/', 
         views.ServiceLevelAgreementBulkImportView.as_view(), name='servicelevelagreement_bulk_import'
    ),
    path('servicelevelagreement/edit/', 
         views.ServiceLevelAgreementBulkEditView.as_view(), name='servicelevelagreement_bulk_edit'
    ),
    path('servicelevelagreement/delete/',
        views.ServiceLevelAgreementBulkDeleteView.as_view(),
        name='servicelevelagreement_bulk_delete',
    ),
    path('servicelevelagreement/<int:pk>/',
        include(get_model_urls('netbox_contracts', 'servicelevelagreement')),
        name='servicelevelagreement',
    ),
    path('servicelevelagreement/<int:pk>/edit/', 
         views.ServiceLevelAgreementEditView.as_view(), name='servicelevelagreement_edit'
    ),
    path('servicelevelagreement/<int:pk>/delete/',
        views.ServiceLevelAgreementDeleteView.as_view(),
        name='servicelevelagreement_delete',
    ),
    path('servicelevelagreement/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='servicelevelagreement_changelog',
        kwargs={'model': models.ServiceLevelAgreement},
    ),
    # Contract assignments
    path('assignments/',
        views.ContractAssignmentListView.as_view(),
        name='contractassignment_list',
    ),
    path('assignments/add/',
        views.ContractAssignmentEditView.as_view(),
        name='contractassignment_add',
    ),
    path('assignments/import/',
        views.ContractAssignmentBulkImportView.as_view(),
        name='contractassignment_bulk_import',
    ),
    path('assignments/edit/',
        views.ContractAssignmentBulkEditView.as_view(),
        name='contractassignment_bulk_edit',
    ),
    path('assignments/delete/',
        views.ContractAssignmentBulkDeleteView.as_view(),
        name='contractassignment_bulk_delete',
    ),
    path('assignments/<int:pk>/',
        views.ContractAssignmentView.as_view(),
        name='contractassignment',
    ),
    path('assignments/<int:pk>/edit/',
        views.ContractAssignmentEditView.as_view(),
        name='contractassignment_edit',
    ),
    path('assignments/<int:pk>/delete/',
        views.ContractAssignmentDeleteView.as_view(),
        name='contractassignment_delete',
    ),
    path('assignments/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='contractassignment_changelog',
        kwargs={'model': models.ContractAssignment},
    ),
    # path('assignments/<int:pk>/contacts/', 
    #      views.ContractAssignmentContactsView.as_view(), 
    #      name='contractassignment_contacts',
    # ),
    # Contract Types
    path('contracttype/',
        views.ContractTypeListView.as_view(),
        name='contracttype_list',
    ),
    path('contracttype/add/',
        views.ContractTypeEditView.as_view(),
        name='contracttype_add',
    ),
    path('contracttype/<int:pk>/',
        views.ContractTypeView.as_view(),
        name='contracttype',
    ),
    path('contracttype/<int:pk>/edit/',
        views.ContractTypeEditView.as_view(),
        name='contracttype_edit',
    ),
    path('contracttype/edit/',
        views.ContractTypeBulkEditView.as_view(),
        name='contracttype_bulk_edit',
    ),
    path('contracttype/<int:pk>/delete/',
        views.ContractTypeDeleteView.as_view(),
        name='contracttype_delete',
    ),
    path('contracttype/delete/',
        views.ContractTypeBulkDeleteView.as_view(),
        name='contracttype_bulk_delete',
    ),
    path('contracttype/import/',
        views.ContractTypeBulkImportView.as_view(),
        name='contracttype_bulk_import',
    ),
    path('contracttype/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='contracttype_changelog',
        kwargs={'model': models.ContractType},
    ),
    # HTMX endpoints
    # path(
    #     'htmx/device/<int:pk>/contracts/',
    #     views.DeviceContractsHTMXView.as_view(),
    #     name='device_contracts_htmx',
    # ),
    # path(
    #     'htmx/device/<int:pk>/contracts/expired/',
    #     views.DeviceContractsExpiredHTMXView.as_view(),
    #     name='device_contracts_expired',
    # ),
    # path(
    #     'htmx/virtualmachine/<int:pk>/contracts/',
    #     views.VirtualMachineContractsHTMXView.as_view(),
    #     name='virtualmachine_contracts_htmx',
    # ),
    # path(
    #     'htmx/virtualmachine/<int:pk>/contracts/expired/',
    #     views.VirtualMachineContractsExpiredHTMXView.as_view(),
    #     name='virtualmachine_contracts_expired',
    # ),
    # Currency
    path('currency/',
        views.CurrencyListView.as_view(),
        name='currency_list'
    ),
    path('currency/add/',
        views.CurrencyEditView.as_view(),
        name='currency_add'
    ),
    path('currency/import/',
        views.CurrencyBulkImportView.as_view(),
        name='currency_bulk_import',
    ),
    path('currency/edit/',
        views.CurrencyBulkEditView.as_view(),
        name='currency_bulk_edit',
    ),
    path('currency/delete/',
        views.CurrencyBulkDeleteView.as_view(),
        name='currency_bulk_delete',
    ),
    path('currency/<int:pk>/',
        views.CurrencyView.as_view(),
        name='currency'
    ),
    path('currency/<int:pk>/edit/',
        views.CurrencyEditView.as_view(),
        name='currency_edit',
    ),
    path('currency/<int:pk>/delete/',
        views.CurrencyDeleteView.as_view(),
        name='currency_delete',
    ),
    path('currency/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='currency_changelog',
        kwargs={'model': models.Currency},
    ),
    # License types
    path('license-types/', views.LicenseTypeListView.as_view(), name='licensetype_list'),
    path('license-types/add/', views.LicenseTypeEditView.as_view(), name='licensetype_add'),
    path(
        'license-types/import/',
        views.LicenseTypeBulkImportView.as_view(),
        name='licensetype_bulk_import',
    ),
    path('license-types/<int:pk>/', views.LicenseTypeView.as_view(), name='licensetype'),
    path('license-types/<int:pk>/edit/', views.LicenseTypeEditView.as_view(), name='licensetype_edit'),
    path('license-types/<int:pk>/delete/', views.LicenseTypeDeleteView.as_view(), name='licensetype_delete'),
    path(
        'license-types/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='licensetype_changelog',
        kwargs={'model': models.LicenseType},
    ),
    # Software licenses
    path('software-licenses/', views.SoftwareLicenseListView.as_view(), name='softwarelicense_list'),
    path('software-licenses/add/', views.SoftwareLicenseEditView.as_view(), name='softwarelicense_add'),
    path(
        'software-licenses/import/',
        views.SoftwareLicenseBulkImportView.as_view(),
        name='softwarelicense_bulk_import',
    ),
    path('software-licenses/<int:pk>/', views.SoftwareLicenseView.as_view(), name='softwarelicense'),
    path('software-licenses/<int:pk>/edit/', views.SoftwareLicenseEditView.as_view(), name='softwarelicense_edit'),
    path(
        'software-licenses/<int:pk>/delete/',
        views.SoftwareLicenseDeleteView.as_view(),
        name='softwarelicense_delete',
    ),
    path(
        'software-licenses/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='softwarelicense_changelog',
        kwargs={'model': models.SoftwareLicense},
    ),
    path(
        'software-licenses/<int:pk>/contracts/',
        views.SoftwareLicenseContractsView.as_view(),
        name='softwarelicense_contracts',
    ),
    # License assignments
    path('license-assignments/', views.LicenseAssignmentListView.as_view(), name='licenseassignment_list'),
    path('license-assignments/add/', views.LicenseAssignmentEditView.as_view(), name='licenseassignment_add'),
    path(
        'license-assignments/import/',
        views.LicenseAssignmentBulkImportView.as_view(),
        name='licenseassignment_bulk_import',
    ),
    path('license-assignments/<int:pk>/', views.LicenseAssignmentView.as_view(), name='licenseassignment'),
    path(
        'license-assignments/<int:pk>/edit/',
        views.LicenseAssignmentEditView.as_view(),
        name='licenseassignment_edit',
    ),
    path(
        'license-assignments/<int:pk>/delete/',
        views.LicenseAssignmentDeleteView.as_view(),
        name='licenseassignment_delete',
    ),
    path(
        'license-assignments/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='licenseassignment_changelog',
        kwargs={'model': models.LicenseAssignment},
    ),
    ]