"""
Demo data for the documentation screenshots, run by make_screenshots.sh on a freshly created database:

    manage.py shell < seed.py

A colocation contract with one line of each billing method, a non-billable child contract, three assigned objects
and three quarterly invoices (two Posted, one Draft) whose lines are generated by the plugin. The primary keys the
screenshots need are written as JSON to $DOCS_IDS_FILE.
"""
import json
import os
from datetime import date
from decimal import Decimal

from circuits.models import Circuit, CircuitType, Provider
from dcim.models import Device, DeviceRole, DeviceType, Manufacturer, Site
from django.contrib.contenttypes.models import ContentType
from tenancy.models import Tenant
from users.models import User

from netbox_contract.models import (
    AccountingDimension,
    BillingMethodChoices,
    Contract,
    ContractAssignment,
    ContractLine,
    ContractType,
    InternalEntityChoices,
    Invoice,
    InvoiceLine,
    InvoiceStatusChoices,
    ServiceProvider,
    StatusChoices,
    Unit,
)
from netbox_contract.services import invoicing

User.objects.create_superuser('admin', 'admin@example.com', 'admin')

# Objects the contract is assigned to
tenant = Tenant.objects.create(name='Corporate IT', slug='corporate-it')
site = Site.objects.create(name='Paris DC1', slug='paris-dc1')
manufacturer = Manufacturer.objects.create(name='Arista', slug='arista')
device_type = DeviceType.objects.create(manufacturer=manufacturer, model='DCS-7050SX3', slug='dcs-7050sx3')
role = DeviceRole.objects.create(name='Core switch', slug='core-switch')
device = Device.objects.create(name='par-core-01', site=site, device_type=device_type, role=role)
carrier = Provider.objects.create(name='Euro Transit', slug='euro-transit')
circuit_type = CircuitType.objects.create(name='Internet transit', slug='internet-transit')
circuit = Circuit.objects.create(cid='ET-PAR-0042', provider=carrier, type=circuit_type)

provider = ServiceProvider.objects.create(
    name='Acme Colocation', slug='acme-colocation', portal_url='https://portal.acme.example'
)
colocation = ContractType.objects.create(name='Colocation', slug='colocation')

dimensions = {
    value: AccountingDimension.objects.create(name=name, value=value)
    for name, value in (('account', '61500'), ('account', '61520'), ('project', 'DC-PARIS'), ('cost center', 'IT-OPS'))
}
units = {
    name: Unit.objects.create(name=name, billing_method=method, months=months)
    for name, method, months in (
        ('Monthly', BillingMethodChoices.RECURRING, 1),
        ('Yearly', BillingMethodChoices.RECURRING, 12),
        ('One-time', BillingMethodChoices.ONE_TIME, None),
        ('Hour', BillingMethodChoices.USAGE, None),
    )
}

common = {
    'contract_type': colocation,
    'external_party_object_type': ContentType.objects.get_for_model(ServiceProvider),
    'external_party_object_id': provider.pk,
    'internal_party': InternalEntityChoices.ENTITY,
    'tenant': tenant,
    'status': StatusChoices.STATUS_ACTIVE,
    'start_date': date(2026, 1, 1),
    'end_date': date(2028, 12, 31),
    'initial_term': 36,
    'renewal_term': 12,
    'notice_period': 90,
    'currency': 'usd',
    'invoice_frequency': 3,
}
contract = Contract.objects.create(
    name='Paris DC1 colocation', external_reference='ACME-2026-0117',
    comments='Two racks in hall B, 5 kW each, with remote hands on demand.', **common,
)
child = Contract.objects.create(name='Paris DC1 cross-connects', parent=contract, billable=False, **common)


def add_line(owner, description, unit, unit_price, quantity, line_dimensions):
    line = ContractLine.objects.create(
        contract=owner, description=description, unit=units[unit], unit_price=Decimal(unit_price),
        quantity=Decimal(quantity), currency=owner.currency, start_date=owner.start_date, end_date=owner.end_date,
    )
    line.accounting_dimensions.set([dimensions[value] for value in line_dimensions])
    return line


rack_space = add_line(contract, 'Rack space, 5 kW', 'Monthly', '1450.00', 2, ('61500', 'DC-PARIS'))
add_line(contract, 'Installation fee', 'One-time', '2500.00', 1, ('61520', 'DC-PARIS'))
add_line(contract, 'Premium support', 'Yearly', '3600.00', 1, ('61500', 'IT-OPS'))
remote_hands = add_line(contract, 'Remote hands', 'Hour', '95.00', 0, ('61520', 'IT-OPS'))
add_line(child, 'Fiber cross-connect', 'Monthly', '120.00', 4, ('61500', 'DC-PARIS'))

for assigned in (device, site, circuit):
    ContractAssignment.objects.create(
        contract=contract, content_type=ContentType.objects.get_for_model(assigned), object_id=assigned.pk
    )

# Invoices are created as the invoice add screen does: lines generated from the contract lines, then the
# hours of remote hands entered, the amount set to the total, and the invoice posted.
invoices = []
for number, start, end, hours, status in (
    ('ACME-INV-2026-001', date(2026, 1, 1), date(2026, 3, 31), 6, InvoiceStatusChoices.STATUS_POSTED),
    ('ACME-INV-2026-002', date(2026, 4, 1), date(2026, 6, 30), 3, InvoiceStatusChoices.STATUS_POSTED),
    ('ACME-INV-2026-003', date(2026, 7, 1), date(2026, 9, 30), 4, InvoiceStatusChoices.STATUS_DRAFT),
):
    invoice = Invoice.objects.create(
        number=number, date=end, period_start=start, period_end=end, currency=contract.currency,
        amount=Decimal('999999'), status=InvoiceStatusChoices.STATUS_DRAFT,
    )
    invoice.contracts.add(contract)
    invoicing.generate_invoice_lines(invoice)
    for invoice_line in InvoiceLine.objects.filter(invoice=invoice, contract_line=remote_hands):
        invoice_line.quantity = Decimal(hours)
        invoice_line.save()
    invoice.amount = sum(line.amount for line in InvoiceLine.objects.filter(invoice=invoice))
    invoice.status = status
    invoice.save()
    invoices.append(invoice)

first_invoice = invoices[0]
ids = {
    'contract': contract.pk,
    'contract_line': rack_space.pk,
    'usage_line': remote_hands.pk,
    'invoice': first_invoice.pk,
    'invoice_line': InvoiceLine.objects.get(invoice=first_invoice, contract_line=rack_space).pk,
}
with open(os.environ['DOCS_IDS_FILE'], 'w') as f:
    json.dump(ids, f)
print(f'Seeded {Contract.objects.count()} contracts, {ContractLine.objects.count()} contract lines, '
      f'{Invoice.objects.count()} invoices, {InvoiceLine.objects.count()} invoice lines: {ids}')
