# Generated by Django 4.0.8 on 2022-12-08 13:04

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0077_customlink_extend_text_and_url'),
        ('tenancy', '0007_contact_link'),
        ('contracts', '0007_alter_invoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internal_partie',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('portal_url', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='contract',
            name='external_partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.serviceprovider'),
        ),
    ]
