# Generated by Django 4.1.5 on 2023-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0007_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
