# Generated by Django 4.0.8 on 2022-12-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_slug_contract_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='slug',
        ),
    ]
