# Generated by Django 4.2.5 on 2023-12-15 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0021_alter_contract_external_partie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='internal_partie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='childs',
                to='netbox_contract.contract',
            ),
        ),
    ]
