# Generated by Django 4.2.10 on 2024-03-29 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'netbox_contract',
            '0023_rename_contractassignement_contractassignment_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='external_partie',
        ),
    ]
