# Generated by Django 5.0.6 on 2024-07-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0030_alter_invoiceline_accounting_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contract',
                to='netbox_contract.invoice',
            ),
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
