# Generated by Django 5.0.6 on 2024-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('extras', '0115_convert_dashboard_widgets'),
        ('netbox_contract', '0034_contract_yrc_alter_contract_mrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdimension',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='accountingdimension',
            constraint=models.UniqueConstraint(
                fields=('name', 'value'), name='unique_accounting_dimension'
            ),
        ),
    ]
