# Generated by Django 5.0.10 on 2025-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            'netbox_contract',
            '0037_contract_notice_period_alter_contract_currency_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingdimension',
            options={'ordering': ('name', 'value')},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ('invoice',)},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='accounting_dimensions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='accounting_dimensions',
        ),
    ]
