# Generated by Django 5.0.10 on 2025-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('netbox_contract', '0038_alter_accountingdimension_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingdimension',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
