# Generated by Django 5.1.5 on 2025-01-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0039_alter_accountingdimension_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
    ]
