# Generated by Django 4.0.8 on 2022-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0038_cabling_cleanup'),
        ('contracts', '0003_rename_contractinvoice_invoice_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='circuit',
        ),
        migrations.AddField(
            model_name='contract',
            name='circuit',
            field=models.ManyToManyField(related_name='contract', to='circuits.circuit'),
        ),
    ]
