# Generated by Django 4.0.8 on 2022-12-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_rename_periode_start_invoice_period_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-period_start',)},
        ),
    ]
